name: Daily Telegram Notification

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Estrattore to update output.html
        run: python EstrattoreGnammoBOT.py

      - name: Read output.html file
        id: read_output
        run: echo "::set-output name=content::$(cat GnammoBOT/output.html)"

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.read_output.outputs.content }}
          format: html