name: Daily Telegram Notification

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Run the workflow manually'

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script 
        run: python EstrattoreGnammoBOT.py

      - name: Save output to file
        run: |
          mkdir -p GnammoBOT
          python -c "import shutil; shutil.move('output.txt', 'GnammoBOT/output.txt')"

      - name: Read output file
        id: read_output_file
        run: echo "::set-output name=content::$(cat GnammoBOT/output.txt)"

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Oggi si mangia:
            ${{ steps.read_output_file.outputs.content }}
