name: Daily Telegram Notification

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script 
        run: python EstrattoreGnammoBOT.py

      - name: Save output to file
        run: |
          mkdir -p GnammoBOT
          python -c "import shutil; shutil.move('output.txt', 'GnammoBOT/output.txt')"

      - name: Read output.txt
        id: read_output
        run: |
          IFS=$'\n'       # Set the input field separator to newline
          output=$(cat GnammoBOT/output.txt)  # Read the content of output.txt
          echo "::set-output name=output::$output"  # Set the output variable
  
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
              <b>Oggi si mangia:</b><pre>${{ github.workspace }}/GnammoBOT/output.txt</pre>